version: "3.7"
services:
  mongo:
    image: mongo
    restart: "always"
    volumes:
      - mongodata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_ROOT_DB:-publisher}
      USER_PASSWORD: ${USER_PASSWORD:-publisher123}
    networks:
      - backend
  api:
    image: node:14.16-slim
    restart: "always"
    ports:
      - "3001:3001"
    working_dir: "/home/node/app"
    volumes:
      - ./api:/home/node/app
    command: [sh, -c, "npm install && npm start"]
    networks:
      - backend
    depends_on:
      - mongo
  nuxt:
    build: ./app/
    restart: always
    ports:
      - "3333:3000"
    command:
      "npm run start"
    environment:
      BASE_URL: ${BASE_URL:-http://api:3001}
    networks:
      - backend
    depends_on:
      - mongo
      - api
volumes: 
  mongodata:
networks:
  backend:
    driver: "bridge"